apiVersion: v1
kind: Service
metadata:
  name: ms-feedback
  labels:
    app: ms-feedback
spec:
  type: NodePort
  selector:
    app: ms-feedback
  ports:
  - port: 8091
    targetPort: 8091
    protocol: TCP
    name: http

